// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awqhszyisfzhasjwugrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3cWhzenlpc2Z6aGFzand1Z3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTQxMTYsImV4cCI6MjA1OTgzMDExNn0.Yyczzt3p-n6WhF1fG0Fu8ZYgLVr29pNwhBajzKA6ujo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);